use std::process::exit;

use clap::Parser as ClapParser;

use crate::camera::KeyboardLayout;

#[derive(ClapParser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    /// Keys used to move camera as a string of (case-insensitive) character symbols.
    #[arg(long, default_value = "wasdqe")]
    movement_keys: String,
    /// Keys used to toggle mouse capture and print camera state as a string of (case-insensitive)
    /// character symbols.
    #[arg(long, default_value = "cpe")]
    other_keys: String,
    /// Use initial scene camera state (generated by pressing p )
    #[arg(long)]
    state: Option<String>,
}

pub fn cli() -> anyhow::Result<()> {
    let args = Args::parse();

    let layout = KeyboardLayout::parse_config(&args.movement_keys, &args.other_keys)
        .unwrap_or_else(|error| {
            eprintln!("Invalid keyboard config: {}", error);
            exit(2)
        });

    crate::run(layout, args.state)
}
