use std::process::exit;

use clap::Parser as ClapParser;

use crate::{
    camera::{Camera, KeyboardLayout},
    scene::Scene,
};

#[derive(ClapParser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    /// Keys used to move camera as a string of (case-insensitive) character symbols.
    #[arg(long, default_value = "wasdqe")]
    movement_keys: String,
    /// Keys used to toggle mouse capture and print camera state as a string of (case-insensitive)
    /// character symbols.
    #[arg(long, default_value = "cpe")]
    other_keys: String,
    /// Use initial scene camera state (generated by pressing p )
    #[arg(long)]
    state: Option<String>,
    /// Path to TOML file containing a scene descriptor. (Should deserialize to `SceneDescriptor` in 'src/scene.rs')
    #[arg(long, required = true)]
    scene: Vec<String>,
}

pub fn cli() -> anyhow::Result<()> {
    let args = Args::parse();

    let layout = KeyboardLayout::parse_config(&args.movement_keys, &args.other_keys)
        .unwrap_or_else(|error| {
            eprintln!("Invalid keyboard config: {}", error);
            exit(2)
        });

    let mut scene = Scene::load_toml(&args.scene.last().unwrap())?;

    scene.camera = args
        .state
        .as_ref()
        .map(|state| Camera::deserialize(&state).unwrap())
        .unwrap_or(scene.camera);

    crate::run(layout, scene)
}
